### ISSUE TITLE
If I want to run the code, where can I get the source data?

### ISSUE THREAD

**Issue by iKaHibi** [EricMiukyQin/Raw_image_processing_pipeline#1]
Hi, Qin!
I wanted to run your code but do not have a camera nearby.
I am wondering if I can get the source data, including the tiff image and csv file somewhere.
Thank you!

**Comment by EricMiukyQin** [comment]
Hi Teaine,
I did not save source data. Sorry about that.

**Comment by wowo68** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
